export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"首页","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"t":"幻灯片页","i":"slides"},["/slides","/slides.md"]],
  ["v-18b24098","/compatibility/for-devices.html",{"t":"兼容性(设备)"},["/compatibility/for-devices","/compatibility/for-devices.md"]],
  ["v-8b1e9810","/compatibility/",{"t":"兼容性"},["/compatibility/index.html","/compatibility/README.md"]],
  ["v-b6fb3f68","/down/all.html",{"t":"所有下载"},["/down/all","/down/all.md"]],
  ["v-26039b12","/down/baidu.html",{"t":"备用链接(百度网盘)"},["/down/baidu","/down/baidu.md"]],
  ["v-14787074","/down/",{"t":"下载"},["/down/index.html","/down/README.md"]],
  ["v-fc0a515c","/down/tools.html",{"t":"工具"},["/down/tools","/down/tools.md"]],
  ["v-737f78c9","/guide/conf.html",{"t":"其他配置(可选)"},["/guide/conf","/guide/conf.md"]],
  ["v-66044b76","/guide/directx.html",{"t":""},["/guide/directx","/guide/directx.md"]],
  ["v-b4c83232","/guide/inst.html",{"t":"安装指南"},["/guide/inst","/guide/inst.md"]],
  ["v-59c59f8e","/guide/touhou.html",{"t":"注意事项"},["/guide/touhou","/guide/touhou.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
